#
# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#

ctrl_interface=/var/run/hostapd
interface=uap0
driver=nl80211
ssid=NXP_WiFi_AP
hw_mode=a
channel=36
beacon_int=100
dtim_period=1
wmm_enabled=1
ignore_broadcast_ssid=0
ieee80211n=1
auth_algs=1
send_probe_response=1
ieee80211ac=1
vht_oper_chwidth=0
vht_oper_centr_freq_seg0_idx=36
ieee80211d=1
country_code=US
ieee80211ax=1
he_su_beamformer=1
he_bss_color=1
he_oper_chwidth=0
he_oper_centr_freq_seg0_idx=36
eapol_version=1
wpa_key_mgmt=WPA-PSK
wpa=2
wpa_pairwise=CCMP
wpa_passphrase=1234567890
